### ISSUE TITLE
slider width relative to the screen width

### ISSUE THREAD

**Issue by grzn** [KevinBatdorf/codaslider#2]
Hi,

I'm trying to put a slider in the middle of the page, and have it take 80% of the window width.

``` css

#container {
    position: fixed;
    top: 20%;
    left: 10%;
    width: 80%;
    height: 70%;
}

.coda-slider-wrapper {
    padding: 0px;
}

#showcase-wrapper #showcase {
    padding: 0px;
    width: 100%;
}

#showcase-wrapper #showcase .panel {
    position: relative;
    width: 100%; /* PROBLEM HERE */
}
```

But this doesn't work, since the panel itself is inside the panel-container.
I'm new to CSS and JS, how can I achieve what I want?
